# Analisis de Componentes Principales - Paso a Paso

* Estandarizar los datos, normalizarlos por columna
* Obtener los vectores y valores propios a partir de la matriz de covarianza o de correlaciones o incluso la tecnica de singular vector decomposition.
* Ordenar los valores propios en ordn descendente y quedarnos con los **p** que se correspondan **a** los **p** mayores y asi disminuir el numero de variables del dataset (p<m)
* Construir la matriz de proyeccion **W** a paritr de los **p** vectores propios
* Transformar el dataset original **X** a traves de **W** para asi obtener datos en el subespacio dimensional de dimension **p** que sera **Y**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../datasets/iris/iris.csv")

In [3]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
X = df.iloc[:,0:4].values
Y = df.iloc[:,4].values

In [11]:
x[0]

array([5.1, 3.5, 1.4, 0.2])

In [12]:
y[0]

'setosa'

In [35]:
import chart_studio.plotly as py
import plotly.graph_objects as go
import plotly.tools as tls

In [36]:
traces = []
legend = {0:False, 1:False, 2:False, 3:False}

colors = {'setosa': 'rgba(255,127,20)',
          'versicolor': 'rgba(31,22,120)',
          'virginica': 'rgba(44,50,180)'}

for col in range(4):
    for key in colors:
        traces.append(go.Histogram(x=X[Y==key, col], opacity = 0.7, xaxis='x%s'%(col+1), marker=dict(color=colors[key]),name = key, showlegend=legend[col]))
        
    legend = {0:False, 1:False, 2:False, 3:False}
        
data = [traces]
layout = go.Layout(barmode='overlay',
                    xaxis=dict(domain=(0,0.25), title='Long, Sepalos (cm)'),
                    xaxis2=dict(domain=(0.3,0.5), title='Anch, Sepalos (cm)'),
                    xaxis3=dict(domain=(0.55, 0.75), title='Long, Petalos(cm)'),
                    xaxis4=dict(domain=(0.8, 1.0), title='Anch, Petalos(cm)'),
                    yaxis=dict(title = 'Numero de ejmplares'),
                    title = 'Distribucion de los rasgos de las diferentes flores Iris')
                                    
fig = go.Figure(data=data, layout =layout)
iplot(fig)

ValueError: 
    Invalid element(s) received for the 'data' property of 
        Invalid elements include: [[Histogram({
    'marker': {'color': 'rgba(255,127,20)'},
    'name': 'setosa',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8, 4.3,
                5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. , 5. , 5.2,
                5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4, 5.1, 5. , 4.5,
                4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ]),
    'xaxis': 'x'
}), Histogram({
    'marker': {'color': 'rgba(31,22,120)'},
    'name': 'versicolor',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([7. , 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1,
                5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
                6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5, 6.1,
                5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7]),
    'xaxis': 'x'
}), Histogram({
    'marker': {'color': 'rgba(44,50,180)'},
    'name': 'virginica',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7,
                5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1,
                6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9,
                5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]),
    'xaxis': 'x'
}), Histogram({
    'marker': {'color': 'rgba(255,127,20)'},
    'name': 'setosa',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. , 3. ,
                4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. , 3.4, 3.5,
                3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3. , 3.4, 3.5, 2.3,
                3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3]),
    'xaxis': 'x2'
}), Histogram({
    'marker': {'color': 'rgba(31,22,120)'},
    'name': 'versicolor',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9,
                2.9, 3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
                2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6, 3. ,
                2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8]),
    'xaxis': 'x2'
}), Histogram({
    'marker': {'color': 'rgba(44,50,180)'},
    'name': 'virginica',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([3.3, 2.7, 3. , 2.9, 3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5,
                2.8, 3.2, 3. , 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. ,
                2.8, 3. , 2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1,
                2.7, 3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ]),
    'xaxis': 'x2'
}), Histogram({
    'marker': {'color': 'rgba(255,127,20)'},
    'name': 'setosa',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1,
                1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6, 1.5,
                1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3, 1.5, 1.3, 1.3,
                1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4]),
    'xaxis': 'x3'
}), Histogram({
    'marker': {'color': 'rgba(31,22,120)'},
    'name': 'versicolor',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([4.7, 4.5, 4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7,
                3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
                4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4, 4.6,
                4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1]),
    'xaxis': 'x3'
}), Histogram({
    'marker': {'color': 'rgba(44,50,180)'},
    'name': 'virginica',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([6. , 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. ,
                5.1, 5.3, 5.5, 6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9,
                5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1,
                5.1, 5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1]),
    'xaxis': 'x3'
}), Histogram({
    'marker': {'color': 'rgba(255,127,20)'},
    'name': 'setosa',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1,
                0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2,
                0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3,
                0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2]),
    'xaxis': 'x4'
}), Histogram({
    'marker': {'color': 'rgba(31,22,120)'},
    'name': 'versicolor',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4,
                1.3, 1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
                1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2, 1.4,
                1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3]),
    'xaxis': 'x4'
}), Histogram({
    'marker': {'color': 'rgba(44,50,180)'},
    'name': 'virginica',
    'opacity': 0.7,
    'showlegend': False,
    'x': array([2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. ,
                2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8,
                2.1, 1.6, 1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3,
                1.9, 2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8]),
    'xaxis': 'x4'
})]]

    The 'data' property is a tuple of trace instances
    that may be specified as:
      - A list or tuple of trace instances
        (e.g. [Scatter(...), Bar(...)])
      - A single trace instance
        (e.g. Scatter(...), Bar(...), etc.)
      - A list or tuple of dicts of string/value properties where:
        - The 'type' property specifies the trace type
            One of: ['area', 'bar', 'barpolar', 'box',
                     'candlestick', 'carpet', 'choropleth',
                     'choroplethmapbox', 'cone', 'contour',
                     'contourcarpet', 'densitymapbox', 'funnel',
                     'funnelarea', 'heatmap', 'heatmapgl',
                     'histogram', 'histogram2d',
                     'histogram2dcontour', 'image', 'indicator',
                     'isosurface', 'mesh3d', 'ohlc', 'parcats',
                     'parcoords', 'pie', 'pointcloud', 'sankey',
                     'scatter', 'scatter3d', 'scattercarpet',
                     'scattergeo', 'scattergl', 'scattermapbox',
                     'scatterpolar', 'scatterpolargl',
                     'scatterternary', 'splom', 'streamtube',
                     'sunburst', 'surface', 'table', 'treemap',
                     'violin', 'volume', 'waterfall']

        - All remaining properties are passed to the constructor of
          the specified trace type

        (e.g. [{'type': 'scatter', ...}, {'type': 'bar, ...}])

## 1.- Calculamos la descomposicion de valores y vectores propios

### a) Usando la Matriz de Covarianzas

In [17]:
from IPython.display import display, Math, Latex
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

$ \sigma_{jk} = \frac{l}{n-1}\sum_{i=1}^m (x_{ij} - \overline{x_j})(x_{ik} - \overline{x_k}) $

$ \Sigma = \frac{1}{n-1}((X-\overline{x})^T(X - \overline{x})) $

$ \overline{x} = \sum_{i=1}^n x_i\in \mathbb R^m $

In [8]:
import numpy as np

In [18]:
mean_vect = np.mean(X_std, axis=0)
mean_vect

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [19]:
cov_matrix = (X_std - mean_vect).T.dot((X_std - mean_vect))/(X_std.shape[0]-1)
cov_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [20]:
np.cov(X_std.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [21]:
eig_values, eig_vectors = np.linalg.eig(cov_matrix)

In [22]:
print("Valores propios \n%s"%eig_values)
print("Valores propios \n%s"%eig_vectors)

Valores propios 
[2.93808505 0.9201649  0.14774182 0.02085386]
Valores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


### b) Usando la Matriz de Correlaciones

In [24]:
corr_matrix = np.corrcoef(X_std.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [25]:
eig_values_corr, eig_vectors_corr = np.linalg.eig(corr_matrix)
print('Valores propios \n%s'%eig_values_corr)
print('Valores propios \n%s'%eig_vectors_corr)

Valores propios 
[2.91849782 0.91403047 0.14675688 0.02071484]
Valores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


### c) Singular Value Deomposition

In [26]:
u,s,v = np.linalg.svd(X_std.T)
u

array([[-0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [ 0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [-0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [-0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [27]:
s

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [28]:
v

array([[ 1.08239531e-01,  9.94577561e-02,  1.12996303e-01, ...,
        -7.27030413e-02, -6.56112167e-02, -4.59137323e-02],
       [-4.09957970e-02,  5.75731483e-02,  2.92000319e-02, ...,
        -2.29793601e-02, -8.63643414e-02,  2.07800179e-03],
       [ 2.72186462e-02,  5.00034005e-02, -9.42089147e-03, ...,
        -3.84023516e-02, -1.98939364e-01, -1.12588405e-01],
       ...,
       [ 5.43380310e-02,  5.12936114e-03,  2.75184277e-02, ...,
         9.89532683e-01, -1.41206665e-02, -8.30595907e-04],
       [ 1.96438400e-03,  8.48544595e-02,  1.78604309e-01, ...,
        -1.25488246e-02,  9.52049996e-01, -2.19201906e-02],
       [ 2.46978090e-03,  5.83496936e-03,  1.49419118e-01, ...,
        -7.17729676e-04, -2.32048811e-02,  9.77300244e-01]])

 ## 2.- Las componentes principales