# El metodo de k-means

In [1]:
import numpy as np

In [3]:
data = np.random.random(90).reshape(30,3)
data

array([[0.43184697, 0.67135373, 0.61863909],
       [0.85330732, 0.65414638, 0.17258375],
       [0.10625859, 0.20688706, 0.23907313],
       [0.41656022, 0.61162343, 0.33398659],
       [0.54653759, 0.59166796, 0.06400591],
       [0.36393022, 0.88341186, 0.55902453],
       [0.86783637, 0.35210965, 0.30272066],
       [0.57565103, 0.625349  , 0.12409192],
       [0.8792865 , 0.49920564, 0.05996951],
       [0.5491354 , 0.48141584, 0.76745156],
       [0.67664054, 0.27658806, 0.32167578],
       [0.8850517 , 0.017758  , 0.62467837],
       [0.17521885, 0.92609973, 0.21866673],
       [0.80664946, 0.80450406, 0.75058329],
       [0.32780947, 0.02256362, 0.14359945],
       [0.91231253, 0.20592898, 0.60684061],
       [0.66411878, 0.03886924, 0.95413273],
       [0.83368769, 0.38690526, 0.80822964],
       [0.92608171, 0.17233456, 0.11077138],
       [0.9913911 , 0.34972046, 0.20417225],
       [0.68891141, 0.94929244, 0.53015965],
       [0.47013815, 0.3625569 , 0.70680838],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2= np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.5491354 , 0.48141584, 0.76745156],
       [0.32780947, 0.02256362, 0.14359945]])

In [7]:
from scipy.cluster.vq import vq

In [9]:
vq(data, clust_centers)

(array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0.2682874 , 0.69008993, 0.3036036 , 0.47161644, 0.6148633 ,
        0.48922753, 0.57815674, 0.65204003, 0.7336951 , 0.        ,
        0.46682192, 0.59008689, 0.79920093, 0.41350215, 0.        ,
        0.48330789, 0.49388109, 0.30259728, 0.61760723, 0.72816026,
        0.54291186, 0.15506646, 0.46578235, 0.30192001, 0.26784381,
        0.30275315, 0.30479088, 0.17400481, 0.30462909, 0.83850574]))

In [10]:
from scipy.cluster.vq import kmeans

In [12]:
kmeans(data, clust_centers)

(array([[0.63746179, 0.46664765, 0.72918243],
        [0.63383471, 0.46680157, 0.18160516]]),
 0.35063492967368115)

In [13]:
kmeans(data, 2)

(array([[0.63746179, 0.46664765, 0.72918243],
        [0.63383471, 0.46680157, 0.18160516]]),
 0.35063492967368115)